Rendered the list to the list page
the-collab-lab/tcl-59-smart-shopping-list pull request #15
Opened 2023-04-04 17:55 UTC by KarenJParker77

_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description

## Related Issue

## Acceptance Criteria

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### Before

### After

## Testing Steps / QA Criteria

2023-04-04 18:31 UTC, mikeyxx commented
Hi Karen and Cassandra... Sandra and I have checked your code and it looks great to us. We wouldn't change anything!

2023-04-05 10:04 UTC, edieblu requested changes
Hello team!

Good job on submitting your first PR! 👏🥳

Before we merge this, we'll need to fix a couple of things. Please go over the comments and let me know if you have any questions. 😊 Once you're ready please request a re-review. Thanks!

2023-04-05 10:04 UTC, edieblu commented on src/views/List.jsx
> +				{data.map((data) => (
To make this easier to read and avoid confusion, it's best to distinguish between the array (`data`) and its values (also called `data` here). 😊

Often the convention is going from plural to singular, for example, if the array is called `books`, then the item would be `book`. Here you could use something like `item`.

2023-04-05 10:04 UTC, edieblu commented on src/views/List.jsx
> +					<ListItem name={data.name} />
When mapping over an array, you need to give each array item a key 😊
There's an error in the console that warns you about that.
<img width="595" alt="image" src="https://user-images.githubusercontent.com/17270662/230048948-09d425af-7c77-47ea-aef0-3ce04596e9fc.png">

You can read more about it [here](https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key).

2023-04-06 08:19 UTC, mikeyxx commented
Hi Karen and Cassandra, your code works fine, to make it more efficient, I think it will be better to use an 'id' as your key. Using the name of the product is fine as there may not be more than one of a product type on the list but I think it is safer to use the product id for the key to help React better identify each item as unique.

If you log out the 'data' value in the console, you will see the data returned has an id value. 


![Screenshot 2023-04-06 091609](https://user-images.githubusercontent.com/79487718/230317455-47008760-7293-4800-a265-3ed876690d0a.jpg)


You can use the 'id' value as the key in the list component

2023-04-06 17:14 UTC, edieblu approved these changes
Great job! 

Please remove the uuid library, and then this is ready to be merged! 🚀

2023-04-06 17:14 UTC, edieblu commented on package.json
> +		"uuid": "^9.0.0"
I think we can remove this 😊

2023-04-06 17:14 UTC, edieblu commented on src/views/List.jsx
> +					<ListItem key={item.id} name={item.name} />
Yes, exactly 👍 Nicely done!

2023-04-06 17:15 UTC, edieblu commented
> Hi Karen and Cassandra, your code works fine, to make it more efficient, I think it will be better to use an 'id' as your key. Using the name of the product is fine as there may not be more than one of a product type on the list but I think it is safer to use the product id for the key to help React better identify each item as unique.
> 
> If you log out the 'data' value in the console, you will see the data returned has an id value.
> 
> ![Screenshot 2023-04-06 091609](https://user-images.githubusercontent.com/79487718/230317455-47008760-7293-4800-a265-3ed876690d0a.jpg)
> 
> You can use the 'id' value as the key in the list component

Thank you @mikeyxx ! 👏

2023-04-06 19:42 UTC, merged